server:
  listen: ":8080"

auth:
  cookie_name: gatekeeper_session
  session_ttl: 24h

upstream:
  target: "http://localhost:3000"

users:
  - username: admin
    # password: "password" -> bcrypt hash below (example)
    password_hash: "$2a$10$6s8G7o0q2qkWg8zFuiYf5OqYfZ0wQ6YQ8p8e1q0aZC3YF1XQzGm8u"

security:
  secure_cookies: false

routes:
  - path: /
    upstream: http://localhost:3000
    auth: true
